### ISSUE TITLE
Matrix Inversion Improvement

### ISSUE THREAD

**Issue by vishnu-dev** [AnalyticsCal/AnalyticsCal-Classroom#20]
**Description**
Matrix inversion code in file [Linear Algebra](https://github.com/AnalyticsCal/AnalyticsCal-Classroom/blob/dev/linear_algebra.py#L61) should be corrected to consume the input (array) and return the results. Currently the code takes `inverse` as input, which doesn't make sense. Also, there is no need for LinearAlgebra being class as the functions under that are more of a utility. For Example, using just the `get_matrix_inverse` function should not involve creating an object.

**To Reproduce**
Call to the function `get_matrix_inverse`

**Expected behaviour**
The expected behaviour is that the function needs to consume array and return inverse array

`inverse = get_matrix_inverse(arr)`

**Comment by kn-neelalohitha** [comment]
@bhavrendra  help him out! 
@vishnu-dev he will help u. The code in [Linear Algebra](https://github.com/AnalyticsCal/AnalyticsCal-Classroom/blob/dev/linear_algebra.py#L61) works fine! The function to get `inverse ` is `getMatrixInverse` -go [here](https://github.com/AnalyticsCal/AnalyticsCal-Classroom/blob/dev/linear_algebra.py#L99.)
I think the way to call it is (not sure):
```python3
import linear_algebra
A = [[a1,a2,a3], [b1,b2,b3], [c1,c2,c3]] # A is the square matrix
order = len(A) # matrix dimension
matrix_operation = linear_algebra.LinearAlgebra(order)
inverse = matrix_operation.getMatrixInverse(A)
```
@bhavrendra  is the above way correct? Please confirm!
Thanks in advance!

**Comment by samta** [comment]
@vishnu-dev pls try to use getMatrixInverse(A), this will expect list of list. Let me know if you have difficulty.
Also regarding the comment on class LinearAlgebra, actually we started with class thinking there will be class-level variables which we might access in other methods. But later we ended up with the current code. I agree there is no need to have a class there, please feel free to enhance the code.

**Comment by vishnu-dev** [comment]
Thanks for the clarification @samta. Will use the `getMatrixInverse` function. 
Marking this as solved @kn-neelalohitha
